### ISSUE TITLE
"My Media" Home Screen is using banner images instead of backdrop

### ISSUE THREAD

**Issue by Akaru-san** [jellyfin/jellyfin-plugin-anilist#51]
First, I'm a novice to these sort of stuff. This issue persists after reinstalling Jellyfin.

![Screenshot 2023-12-18 065223](https://github.com/jellyfin/jellyfin-web/assets/58054989/b398aa52-3cda-45b7-9c6b-479fc30c43b8)

Whenever I tried to delete and scan for a new one, "My Media" images will be replaced with banner size images. It also happens when creating a new library.

![Screenshot 2023-12-20 102618](https://github.com/jellyfin/jellyfin-web/assets/58054989/1a8d9312-b08d-4999-9c04-4c33e8ea697b)
![Screenshot 2023-12-21 210846](https://github.com/jellyfin/jellyfin-web/assets/58054989/b79818d2-04ac-4656-a25a-473ea81f1292)

Using the "Edit Images" feature is odd.
      Searching for a backdrop returns banner size images
      Searching for a banner return nothing.
      Searching Clearart, Box, Disc ,Logo, Menu, Screenshot, Thumb also returns nothing.
      Only Primary images is consistent.
Recently I noticed the Fanart plugin is recognized but not being used?

Specs: Asustor NAS - running docker
Version: 10.8.13.r01
Plugins: AniDB, AniList, Fanart, Jelly Skin Manager

**Comment by Adaptz** [comment]
Yep getting the same issue still, with the 7.0.0 update not working included as well.

**Comment by AkaTenshi** [comment]
This seems to be a side-effect of #37, where the banner set as backdrop.
Now the images on the series-overview page better match AniList.
The only supported image types of this plugin are primary (AniList cover) and backdrop (AniList banner).
Therefore all other types return no results.
But I don't know why "My Media" uses backdrops instead of primary images.
Maybe this should be a library-level setting?

**Comment by Akaru-san** [comment]
I just resort to manually add the images myself. I understand if it's just Anilist but also not having AniDB and Fanart plugin to work is weird. Probably just an Asustor problem.
